### ISSUE TITLE
How do I run without docker support

### ISSUE THREAD

**Issue by Zumbalamambo** [ColeMurray/medium-facenet-tutorial#1]
Im wanting to run the code without docker . How can I be able to do so?

**Comment by ColeMurray** [comment]
Hello Zumbalamambo,

To run without docker, you'll need:
- install dlib from source. 
  -Installation can be found here http://dlib.net/
- install opencv from source
  - http://opencv.org/
- install requirements.txt

If you are on ubuntu, you can copy the commands from `Dockerfile` and run them manually.
