### ISSUE TITLE
Can't open file error when trying to getting results

### ISSUE THREAD

**Issue by VinodPathak** [ColeMurray/medium-facenet-tutorial#11]
I faced same issue https://github.com/ColeMurray/medium-facenet-tutorial/issues/2. But No solution provided and it was closed without providing resolution.

**Comment by VinodPathak** [comment]
I got the solution, Install dockerimage where you have your Scripts. And Scripts will run.

**Comment by aeroprez** [comment]
@VinodPathak I'm having this issue too. can you please elaborate on this fix? I googled "install dockerimage" and it's no help. I placed the dockerfile in the folder with my scripts and I still can't get results. Just repeatedly can't find train_classifier. Please help !
