### ISSUE TITLE
About:Skipping Input

### ISSUE THREAD

**Issue by ATPNazlit** [ColeMurray/medium-facenet-tutorial#12]
Hi
Why does the algorithm skips some inputs even though it is able to capture the face and crop correctly?
I have tried to extend the dataset by adding some more training samples but the algorithm does not take into account these samples?

**Comment by ColeMurray** [comment]
Hello @ATPNazlit,

There are two locations where input can be filtered.

This line filters any images that could not be aligned.
https://github.com/ColeMurray/medium-facenet-tutorial/blob/master/medium_facenet_tutorial/preprocess.py#L52

This line filters out classes with less than the minimum input amount.
https://github.com/ColeMurray/medium-facenet-tutorial/blob/master/medium_facenet_tutorial/lfw_input.py#L109

**Comment by ATPNazlit** [comment]
Thank you so much . I am sorry i did not read the code in detail before testing with the thought of a bug. It is my fault. 
Take care

Nazli
