### ISSUE TITLE
Loading model taking too long

### ISSUE THREAD

**Issue by chetandev** [ColeMurray/medium-facenet-tutorial#14]
``` 
 model_exp = os.path.expanduser('etc/20170511-185253/20170511-185253.pb')
 if os.path.isfile(model_exp):
     logging.info('Model filename: %s' % model_exp)
     print("loading model to graph")
     with gfile.FastGFile(model_exp, 'rb') as f:
         graph_def = tf.GraphDef()
         graph_def.ParseFromString(f.read())
         tf.import_graph_def(graph_def, name='')
 else:
     logger.error('Missing model file. Exiting')
     sys.exit(-1)
```

this code is taking around 18 secs . how can we optimize it ?

**Comment by ColeMurray** [comment]
@chetandev,

You could optimize the loading by reducing the size of the graph / using a smaller model to perform the embedding process. When doing so, you will incur worse performance.

Additionally, you can persist the model in memory to incur this 18 seconds 1 time only.
