### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by eisaanis2** [ColeMurray/medium-facenet-tutorial#15]
`File "/medium-facenet-tutorial/medium_facenet_tutorial/train_classifier.py", line 207, in <module>
    min_images_per_labels=args.min_images_per_class, split_ratio=args.split_ratio, is_train=args.is_train)
  File "/medium-facenet-tutorial/medium_facenet_tutorial/train_classifier.py", line 66, in main
    logger.info('Created {} embeddings'.format(len(emb_array)))
    TypeError: object of type 'NoneType' has no len()`

Getting this error on the final step,please help. If you are willing,you can also remotely connect to my system and check things out.Thank you.

**Comment by ColeMurray** [comment]
Hello Eisaanis2,

This error is typically caused when the data directory is not properly created.

EDIT:
Discussed offline. Issue was related to system not detecting data directory. Directory was changed and completed successfully.
