### ISSUE TITLE
Taking too long in Training

### ISSUE THREAD

**Issue by AssassinAsh** [ColeMurray/medium-facenet-tutorial#18]
![screenshot from 2018-10-30 19-59-34](https://user-images.githubusercontent.com/43932463/47725376-74e5b000-dc7e-11e8-8a01-0633d90d306f.png)

Taking too long to train and I have no idea how much iterations more?

**Comment by ColeMurray** [comment]
Hey @AssassinAsh ,

Can you provide additional information related to your training?

Please provide:
* Command listed to run training
* Information about what dataset is being trained on

Thank you,

Cole Murray

**Comment by AssassinAsh** [comment]
I'm following the exact procedure that's provided [here](https://hackernoon.com/building-a-facial-recognition-pipeline-with-deep-learning-in-tensorflow-66e7645015b8).

> docker run -v $PWD:/medium-facenet-tutorial \
-e PYTHONPATH=$PYTHONPATH:/medium-facenet-tutorial \
-it colemurray/medium-facenet-tutorial \
python3 /medium-facenet-tutorial/medium_facenet_tutorial/train_classifier.py \
--input-dir /medium-facenet-tutorial/output/intermediate \
--model-path /medium-facenet-tutorial/etc/20170511-185253/20170511-185253.pb \
--classifier-path /medium-facenet-tutorial/output/classifier.pkl \
--num-threads 16 \
--num-epochs 25 \
--min-num-images-per-class 10 \
--is-train 

This is the part where I'm facing problem. The dataset is also the one provided in the above link.

**Comment by ColeMurray** [comment]
Closing due to my late response. Please reopen if still working and need help.
