### ISSUE TITLE
Can't open file error when trying to getting results

### ISSUE THREAD

**Issue by LisySamuel92** [ColeMurray/medium-facenet-tutorial#2]
python3: can't open file '/medium-facenet-tutorial/medium_facenet_tutorial/preprocess.py': [Errno 2] No such file or directory
i created these files but it repeatedly producing this error i really don't know what to do for this

**Comment by aeroprez** [comment]
@LisySamuel92 could you please say how you fixed this? I looked at the other thread under your post but can't figure that one out either.
