### ISSUE TITLE
Dataset used in tutorial

### ISSUE THREAD

**Issue by xichengc** [ColeMurray/medium-facenet-tutorial#3]
Hi,

Awesome work!
In the tutorial(https://hackernoon.com/building-a-facial-recognition-pipeline-with-deep-learning-in-tensorflow-66e7645015b8).
The dataset used for training and prediction is the same one `/medium-facenet-tutorial/output/intermediate`
I am trying to use my own dataset which contains only one image. I have cropped them using the preprocessing mechanism provided in the tutorial, but the prediction returned an error that shows the emb_array is None.

Could you please help.
Thanks,
Xicheng

**Comment by ColeMurray** [comment]
Hello Xicheng,

Quick checklist:

* Is the directory structure of your dataset formatted properly?
** Please provide information on how you are structuring this
* Is the image you are preprocessing processed successfully?
* On line 138 of train_classifier.py, what does the log statement show?
** ``` logger.info('Processing iteration {} batch of size: {}'.format(i, len(batch_labels)))```
* What is the output of line 46 of `train_classifier.py`?
** Add print(images,labels,class_names) after this line
* Please provide the command run when evaluating your dataset

**Comment by xichengc** [comment]
Hi Cole,

Never mind. I found out that it splits the dataset by a ratio and my dataset was too small(1 file) to form a test_set. Changed the code a little bit then it works. I am closing this issue, thanks.

**Comment by tushalien** [comment]
@xichengc  can you please help with the changed code for testing a single image ?
