### ISSUE TITLE
different prediction probability for the same test image 

### ISSUE THREAD

**Issue by rakshitajain5** [ColeMurray/medium-facenet-tutorial#4]
Hi,
I have created a pickle based on my own dataset. When I am running the code for the same test image, I am getting different prediction probability every time. This is due to the different emb_array created (each time for the same image). Why is this happening when all my inputs are same?

**Comment by ColeMurray** [comment]
Hello Rakshita,

Randomness is introduced in two spots in the code. The first takes place on the random transformations; specifically random_crop (line 42 https://gist.github.com/ColeMurray/db68136296f15a7d28b6994663a22303#file-lfw_input-py)

The second spot of randomness is in the SVC model. Documentation can be found here, specifically, the random_state parameter: http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

**Comment by rakshitajain5** [comment]
Thanks, after removing the random_crop function I am getting the same embedding for a particular image. Why are random transformations needed?

**Comment by rakshitajain5** [comment]
Thanks, after removing the random_crop function I am getting the same embedding for a particular image. Why are random transformations needed?
